# Generated by Django 6.0.3 on 2026-06-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_link",
            field=models.URLField(
                blank=True, max_length=1000, null=True, verbose_name="ссылка на оплату"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "создан"),
                    ("open", "ожидает оплаты"),
                    ("paid", "оплачен"),
                    ("unpaid", "не оплачен"),
                    ("canceled", "отменён"),
                ],
                default="created",
                max_length=20,
                verbose_name="статус платежа",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_price_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ID цены Stripe"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_product_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ID продукта Stripe"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_session_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ID сессии Stripe"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "наличные"),
                    ("transfer", "перевод на счет"),
                    ("stripe", "Stripe"),
                ],
                default="stripe",
                max_length=20,
                verbose_name="способ оплаты",
            ),
        ),
    ]
