[project]
name = "homework30+"
version = "0.1.0"
description = ""
authors = [
    {name = "Timofey",email = "mr.tim.iv@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "celery>=5.6.0",
    "django-celery-beat>=2.8.1",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
