# Generated by Django 6.0.3 on 2026-06-23 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0004_alter_course_options_alter_lesson_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="last_notification_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="дата последнего уведомления об обновлении",
            ),
        ),
    ]
