# Generated by Django 6.0.3 on 2026-06-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0005_course_last_notification_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="дата обновления"),
        ),
    ]
